### ISSUE TITLE
IBM gaiandb libraries

### ISSUE THREAD

**Issue by RezaMoosa** [gaiandb/gaiandb#24]
Hi David

I have created a sample VTI for connection of Gaiandb to SOLID server and I'm working on its improvement. For building of Gaiandb I am looking for some libraries and dependencies created by IBM. I would really appreciate your advice how I can find them:

com.ibm.siapi
com.ibm.juno
com.ibm.mqtt
com.ibm.watson
com.ibm.es

Thank you for your time.

Kind regards
Reza

**Comment by drvyvyan** [comment]
@RezaMoosa - I'm closing this issue as it is not distinct but rather a step for https://github.com/gaiandb/gaiandb/issues/22 - these dependency packages all relate to peripheral capability - not to the core of gaiandb - you can just comment out code that references classes in these packages - siapi/juno relate most closely to your purpose (respectively for text index search / JSON handling) however you are using REST to access the SOLID data so you can just use java input/output streams to the endpoints.
